name: Test

on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  order1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bazelisk clean --expunge
          bazelisk build --cpu=darwin_arm64 -s //:get_cpu_info
          cat bazel-bin/cpu_info.txt
        env:
          USE_BAZEL_VERSION: last_rc
      - run: |
          bazelisk clean --expunge
          bazelisk build --cpu=darwin_arm64 -s //:get_cpu_info
          cat bazel-bin/cpu_info.txt
        env:
          USE_BAZEL_VERSION: last_green

  order2:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bazelisk clean --expunge
          bazelisk build --cpu=darwin_arm64 -s //:get_cpu_info
          cat bazel-bin/cpu_info.txt
        env:
          USE_BAZEL_VERSION: last_green
      - run: |
          bazelisk clean --expunge
          bazelisk build --cpu=darwin_arm64 -s //:get_cpu_info
          cat bazel-bin/cpu_info.txt
        env:
          USE_BAZEL_VERSION: last_rc

  just-one:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bazelisk clean --expunge
          bazelisk build --cpu=darwin_arm64 -s //:get_cpu_info
          cat bazel-bin/cpu_info.txt
