name: Test

on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  cpu:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bazelisk clean --expunge
          bazelisk build --cpu=darwin_arm64 -s //:get_cpu_info
          bazelisk build --cpu=darwin_arm64 -s @subproject//:get_cpu_info
          cat bazel-bin/cpu_info.txt

  platforms:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bazelisk clean --expunge
          bazelisk build --platforms=//:darwin_arm64 -s //:get_cpu_info
          bazelisk build --platforms=//:darwin_arm64 -s @subproject//:get_cpu_info
          cat bazel-bin/cpu_info.txt
