name: Test

on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        bazel build --cpu=darwin_arm64 -s @subrepo//:get_cpu_info
        cat bazel-bin/external/subrepo/cpu_info.txt
