name: Test

on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bazel build --cpu=darwin_arm64 -s @llvm-project//llvm:tblgen
